version = 0.1
[default.deploy.parameters]
stack_name = "photo-app-cognito"
resolve_s3 = true
s3_prefix = "photo-app-cognito"
region = "ap-southeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
confirm_changeset = true
